name: helm-template-and-push

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      repository:
        required: true
        type: string
      destination_repo:
        required: true
        type: string
      destination_branch:
        required: true
        type: string
      destination_folder:
        required: true
        type: string
      commit_message:
        required: true
        type: string
      user_email:
        required: true
        type: string
      user_name:
        required: true
        type: string
    secrets:
      git_token:
        required: true

jobs:
  helm-template-and-push:
    name: Generate Helm template and Git push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.git_token }}

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: Update Helm dependencies
        working-directory: ./deployment
        run: helm dep update

      - name: Generate Helm template
        working-directory: ./deployment
        run: helm template -f values.local.yaml ${{ inputs.service_name }} . > ${{ inputs.service_name }}.yaml

      - name: Push template into destination repo
        uses: dmnemec/copy_file_to_another_repo_action@eebb594efdf52bc12e1b461988d7254322dac131
        env:
          API_TOKEN_GITHUB: ${{ secrets.git_token }}
        with:
          source_file: './deployment/${{ inputs.service_name }}.yaml'
          destination_repo: '${{ inputs.destination_repo }}'
          destination_branch: '${{ inputs.destination_branch }}'
          destination_folder: '${{ inputs.destination_folder }}'
          user_email: '${{ inputs.user_email }}'
          user_name: '${{ inputs.user_name }}'
          commit_message: '${{ inputs.commit_message }}'
