name: update-fulfillment-integration

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      namespace:
        required: false
        default: fulfillment
        type: string
      image_tag:
        required: false
        type: string        
    secrets:
      git_token:
        required: true

jobs:
  update-fulfillment-integration-repo:
    name: Generate Helm template and Git push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'main'

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: Update Helm dependencies
        working-directory: ./deployment
        run: helm dep update

      - name: Generate Helm template
        working-directory: ./deployment
        run: helm template -f values.integration.yaml ${{ inputs.service_name }} --set fabric-chart.resources.requests.cpu=1m,fabric-chart.resources.requests.memory=1Mi,dafka-producer.resources.requests.cpu=1m,dafka-consumer.resources.requests.cpu=1m . > ${{ inputs.service_name }}.yaml

      - name: Push template into destination repo
        uses: dmnemec/copy_file_to_another_repo_action@eebb594efdf52bc12e1b461988d7254322dac131
        env:
          API_TOKEN_GITHUB: ${{ secrets.git_token }}
        with:
          source_file: './deployment/${{ inputs.service_name }}.yaml'
          destination_repo: 'get-fabric/fulfillment-integration'
          destination_branch: 'main'
          destination_folder: 'deployments/${{ inputs.namespace }}'
          user_email: 'fulfillment-integration@getfabric.com'
          user_name: 'fulfillment-integration'
          commit_message: 'updated ${{ inputs.service_name }}'
