name: update-fulfillment-integration

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      commit_message:
        required: true
        type: string
    secrets:
      git_token:
        required: true

jobs:
  update-fulfillment-integration-repo:
    name: Generate Helm template and Git push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: get-fabric/${{ inputs.service_name }}
          token: ${{ secrets.git_token }}

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: latest

      - name: Update Helm dependencies
        working-directory: ./deployment
        run: helm dep update

      - name: Generate Helm template
        working-directory: ./deployment
        run: helm template -f values.integration.yaml ${{ inputs.service_name }} . > ${{ inputs.service_name }}.yaml

      - name: Push template into destination repo
        uses: dmnemec/copy_file_to_another_repo_action@eebb594efdf52bc12e1b461988d7254322dac131
        env:
          API_TOKEN_GITHUB: ${{ secrets.git_token }}
        with:
          source_file: './deployment/${{ inputs.service_name }}.yaml'
          destination_repo: 'get-fabric/fulfillment-integration'
          destination_branch: 'main'
          destination_folder: 'deployments'
          user_email: 'fulfillment-integration@getfabric.com'
          user_name: 'fulfillment-integration'
          commit_message: '${{ inputs.commit_message }}'
